### ISSUE TITLE
The font size is too large

### ISSUE THREAD

**Issue by Paper-wand** [macimas/macsMinecraft#1]
First of all thank you for making this font. But I found some problems with it.

Mac's Minecraft compared to other fonts under the same font size:
<img width="811" alt="截屏2024-02-23 18 19 42" src="https://github.com/macimas/macsMinecraft/assets/112165427/c1046d12-e624-4233-b207-b334f43299fd">
Obviously, Mac's Minecraft is much bigger than other fonts:
This causes Mac's Minecraft to look higher and less harmonious when mixed with other fonts.
_(Mac's Minecraft + Noto Sans)_
<img width="981" alt="截屏2024-02-23 18 29 42" src="https://github.com/macimas/macsMinecraft/assets/112165427/fdc36870-377f-432b-a111-de98163dcff7">
<img width="983" alt="截屏2024-02-23 18 31 53" src="https://github.com/macimas/macsMinecraft/assets/112165427/761989b2-6b88-4070-851e-00cf1e70273c">
This might be better:
_(Mojangles (Extracted from Minecraft apk) + Noto Sans)_
<img width="932" alt="截屏2024-02-23 18 35 58" src="https://github.com/macimas/macsMinecraft/assets/112165427/c1a15f1f-d991-4f65-ac59-4b777e9ea5d0">
<img width="928" alt="截屏2024-02-23 18 36 10" src="https://github.com/macimas/macsMinecraft/assets/112165427/68b04b3b-0c63-4724-ac8e-62129db8004a">
So can you solve this problem?

I also found that "p" and "q" in Mac's Minecraft is one pixel longer than ones in original Minecraft Seven. Was it intentional or unintentional?
_(In game)_
<img width="317" alt="截屏2024-02-23 17 41 14" src="https://github.com/macimas/macsMinecraft/assets/112165427/aeee434a-3665-4566-a785-5e2f1dc5d529">
_(Mac's Minecraft)_
<img width="481" alt="截屏2024-02-23 17 48 28" src="https://github.com/macimas/macsMinecraft/assets/112165427/171c9d24-a372-4274-8ef3-6f0df31ff796">

**Comment by macimas** [comment]
hi! sorry for the late response, i don't often check my github notifications :sweat_smile:

i'm not sure if i can do much about the font size.
here's some very zoomed-in text (500%) in Figma, the tool i use
for comparison there's text with adjusted font size on my font, roughly emulating the font you used
when you see it in vectors, they'll look fine
![image](https://github.com/macimas/macsMinecraft/assets/42163944/eb545f36-2f88-4407-bcc4-9ddc718d0308)

although generally people wouldn't have their fonts massively zoomed in like that
if you were to screenshot it at 100% zoom, then zoom that at 500%, it would look quite bad
this is more of a worse case scenario and nitpicky, however i don't really like the font not being pixel perfect, and would prefer to keep it that way
![image](https://github.com/macimas/macsMinecraft/assets/42163944/17d48435-b86a-4a4e-9a2e-1c95e84e8072)

it's less bad if you look at it at 100% zoom, but i still dont really like that
![image](https://github.com/macimas/macsMinecraft/assets/42163944/a11ea559-0d85-4a55-b3a1-e04d93d5f568)


"p" and "q" being 1 pixel longer however is definitely an oversight. i'll fix that in a bit!

**Comment by macimas** [comment]
fixed in 1.1

**Comment by braainsiogame** [comment]
minecraft chunk animator
